version: '2'
services:
  app:
    build: .
    container_name: metabaron
    command: bash -c "/code/gunicorn_start.sh"
    expose:
      - "8000"
    environment:
      - DJANGO_SETTINGS_MODULE=metabaron.settings.dockercompose
    volumes:
      - /Users/dbernick/Code/sharedstatic:/code/static
  server:
    image: nginx
    links: 
      - app:app
    ports:
      - "80:80"
    volumes:
      - ./scripts/nginx.conf:/etc/nginx/conf.d/app.conf
      - /Users/dbernick/Code/sharedstatic:/code/static
      
    
