# Generated by Django 2.0.4 on 2018-04-11 17:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lookup',
            name='method',
            field=models.CharField(choices=[('GET', 'GET'), ('POST', 'POST')], help_text='HTTP method of access of URL', max_length=5),
        ),
        migrations.AlterField(
            model_name='lookup',
            name='paramname',
            field=models.CharField(help_text="What is the parameter name for the access_token to passed to URL (usually it's something like access_token)", max_length=100),
        ),
        migrations.AlterField(
            model_name='lookup',
            name='paramtype',
            field=models.CharField(choices=[('COOKIE', 'cookie'), ('QUERY', 'query string'), ('HEADER', 'HTTP Header')], help_text='How is access_token passed to URL', max_length=10),
        ),
        migrations.AlterField(
            model_name='lookup',
            name='short_id',
            field=models.CharField(help_text='a short_id that will be used for lookups', max_length=200, unique=True, validators=[django.core.validators.RegexValidator(code='invalid short_id', message='short_id must be Alphanumeric', regex='^[a-zA-Z0-9]*$')]),
        ),
        migrations.AlterField(
            model_name='lookup',
            name='url',
            field=models.CharField(help_text='full /userinfo URL of OIDC provider', max_length=200),
        ),
    ]
