# Generated by Django 2.0.4 on 2018-05-03 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0003_auto_20180412_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='lookup',
            name='paramtype',
            field=models.CharField(choices=[('COOKIE', 'cookie'), ('QUERY', 'query string'), ('HEADER', 'HTTP Header')], default='QUERY', help_text='How are we passing the token to the introspector?', max_length=100),
        ),
    ]
