# Generated by Django 2.0.4 on 2018-05-07 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0004_lookup_paramtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='JWKSUri',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('URL', models.URLField(blank=True, help_text='JWKS URI', null=True, unique=True)),
            ],
        ),
    ]
